---
title: "Pre-workshop instructions"
---

Prior to the workshop, please decide whether you would like to use your own setup or use Posit Cloud. Then, follow the steps accordingly.

## Own setup

If you would like to use your own setup, please complete the following steps prior to the workshop:

-   Download and install the latest versions of R, RStudio, and Quarto:

    -   R `4.2` or above: <https://cran.r-project.org>
    -   RStudio `2023.03.1+446` or above: <https://posit.co/download/rstudio-desktop>
    -   Quarto `1.3.354` or above: <https://quarto.org/docs/get-started>

-   Install the following packages:

```{r}
#| eval: false

pkg_list <- c(
  "tidyverse", "gt", "ggthemes", "palmerpenguins", "quarto", "here"
)
install.packages(pkg_list)
```

-   Download `exercises.zip` at <https://mine.quarto.pub/quarto-monash/exercises.zip> and unzip it on your Desktop or somewhere you can easily locate on your computer. Then, go to RStudio \> File \> New Project \> Existing Directory and navigate to the unzipped `exercises` folder and create an RStudio project in there and open it.

## Posit Cloud

If you would like to use Posit Cloud, [click here to join the Posit Cloud space for the workshop](https://posit.cloud/spaces/381590/join?access_code=Ls8BhVUk--q9R03Bzadl4KUkkURdcXtGUwOjExWT).
